### PR TITLE
Additional options and caching

### PR DESCRIPTION
**Pull request by FDIM**
Few new features (all optional):
- caching - to save IO on each call
- ability to preprocess template - needed a hook :)
- customizable paths from where templates are included

Let me know what you think. Tests are updated as well, but I am thinking of converting them to jasmine. 

Lastly, for v3, it might be a good idea to convert all sync calls to async so that async file apis could be used. At the same time caching with memcached would also become possible.

### CODE REVIEW

**Comment by allenhwkim** [comment]
Thanks for this upgrade @FDIM I haven't thoroughly read your code, but since the test is passing I am all good with the changes.

**Comment by allenhwkim** [comment]
You can publish this since you are the owner of npm too. 
image

**Comment by FDIM** [comment]
Yep, I am aware of that @allenhwkim just wanted to get some feedback from you.

**Comment by allenhwkim** [comment]
All changes looks good on me. We should release as 2.1.0 since it's not just bug fixes.

**Pull request merged**
